compiler: clang
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- sudo add-apt-repository -y ppa:beineri/opt-qt532
- sudo apt-get update
- sudo apt-get -y install alsa-base alsa-utils libasound2 libasound2-dev
- sudo apt-get -y install qt53declarative
- sudo apt-get -y install pep8 pyflakes libpulse-dev
- sudo apt-get -y install qt53quickcontrols qt53graphicaleffects
- sudo apt-get -y install qt53tools
script:
- source /opt/qt53/bin/qt53-env.sh
- qmake -spec linux-clang
- make check

notifications:
  slack: papyros:qTNflfj4wj3AcYKLJJdpKOa4
