language: cpp
compiler: gcc
install:
 - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update
 - sudo apt-get -y install qt5-default qtdeclarative5-dev qtdeclarative5-qtquick2-plugin
script:
 - qmake
 - make check
